# Generated by Django 2.2 on 2020-01-27 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nom_autor', models.CharField(max_length=30)),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Autores',
                'verbose_name': 'Autor',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nom_genero', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('total_libros', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120)),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo_electronico', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=10)),
                ('num_libros', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Libros_subidos',
            fields=[
                ('id_libro_subido', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=500)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('correo_electronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Usuario')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id_intercambio', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('SOL', 'Solicitado'), ('PRE', 'Prestado'), ('DEV', 'Devuelto'), ('NEG', 'Negado')], default='SOL', max_length=3)),
                ('fecha_solicitud', models.DateTimeField(auto_now=True)),
                ('fecha_prestamo', models.DateTimeField(blank=True)),
                ('fecha_devolucion', models.DateTimeField(blank=True)),
                ('calificacion1', models.FloatField(blank=True)),
                ('calificacion2', models.FloatField(blank=True)),
                ('comentario1', models.CharField(blank=True, max_length=500)),
                ('comentario2', models.CharField(blank=True, max_length=500)),
                ('correo_electronico1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correo_electronico1', to='ProyectoSharing.Usuario')),
                ('correo_electronico2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correo_electronico2', to='ProyectoSharing.Usuario')),
                ('id_libro_subido1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_libro_subido1', to='ProyectoSharing.Libros_subidos')),
                ('id_libro_subido2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_libro_subido2', to='ProyectoSharing.Libros_subidos')),
            ],
            options={
                'verbose_name_plural': 'Intercambios',
                'verbose_name': 'Intercambio',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.FloatField()),
                ('comentario', models.CharField(max_length=500)),
                ('correo_electronico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Usuario')),
                ('id_libro_subido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libros_subidos')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
                'verbose_name': 'Calificación',
            },
        ),
        migrations.CreateModel(
            name='Autor_Libro',
            fields=[
                ('id_autor_libro', models.AutoField(primary_key=True, serialize=False)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Autor')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libro')),
            ],
            options={
                'verbose_name_plural': 'Autores_Libros',
                'verbose_name': 'Autor_Libro',
            },
        ),
    ]
