# Generated by Django 2.2 on 2020-01-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='calificacion',
            options={'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nomb_autor',
            new_name='nom_autor',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='Telefono',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='libros_subidos',
            name='id_Libro',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='id_genero',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Genero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros_subidos',
            name='id_libro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_autor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autor_libro',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Autor'),
        ),
        migrations.AlterField(
            model_name='autor_libro',
            name='id_autor_libro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autor_libro',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libro'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='id_calificacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libro'),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Usuario'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id_genero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='total_libros',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='id_intercambio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='id_libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libro'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='id_usuario1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario1', to='ProyectoSharing.Usuario'),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='id_usuario2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario2', to='ProyectoSharing.Usuario'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_libro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libros_subidos',
            name='id_libro_subido',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libros_subidos',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_libros',
            field=models.IntegerField(default=0),
        ),
    ]
