# Generated by Django 2.2 on 2020-02-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='calificacion1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
