# Generated by Django 2.2 on 2020-01-19 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0002_auto_20200116_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor_libro',
            options={'verbose_name': 'Autor_Libro', 'verbose_name_plural': 'Autores_Libros'},
        ),
        migrations.AlterModelOptions(
            name='intercambio',
            options={'verbose_name': 'Intercambio', 'verbose_name_plural': 'Intercambios'},
        ),
        migrations.RenameField(
            model_name='autor_libro',
            old_name='id_libro',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='libros_subidos',
            old_name='id_libro',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellido_usuario',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nom_usuario',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='id_libro',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='id_libro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='Titulo',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='id_libro',
        ),
        migrations.RemoveField(
            model_name='libros_subidos',
            name='estado',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='id_libro_subido',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='ProyectoSharing.Libros_subidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambio',
            name='comentario1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='comentario2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='estado',
            field=models.CharField(choices=[('SOL', 'Solicitado'), ('PRE', 'Prestado'), ('DEV', 'Devuelto'), ('NEG', 'Negado')], default='SOL', max_length=3),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambio',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='intercambio',
            name='id_libro_subido1',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='id_libro_subido1', to='ProyectoSharing.Libros_subidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambio',
            name='id_libro_subido2',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='id_libro_subido2', to='ProyectoSharing.Libros_subidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(default="act_bd", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libros_subidos',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(default="act_bd", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default="act_bd", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='comentario',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='calificacion1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='calificacion2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libros_subidos',
            name='descripcion_estado',
            field=models.CharField(max_length=500),
        ),
    ]
