# Generated by Django 2.2 on 2020-02-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0002_auto_20200205_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='calificacion2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
