# Generated by Django 2.2 on 2020-02-05 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0003_auto_20200205_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='id_libro_subido1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_libro_subido1', to='ProyectoSharing.Libros_subidos'),
        ),
    ]
