# Generated by Django 2.2 on 2020-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0004_auto_20200205_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
