# Generated by Django 2.2 on 2020-01-25 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0004_auto_20200125_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros_subidos',
            old_name='id_usuario',
            new_name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='id_usuario1',
        ),
        migrations.RemoveField(
            model_name='intercambio',
            name='id_usuario2',
        ),
        migrations.AddField(
            model_name='intercambio',
            name='correo_electronico1',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='correo_electronico1', to='ProyectoSharing.Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intercambio',
            name='correo_electronico2',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='correo_electronico2', to='ProyectoSharing.Usuario'),
            preserve_default=False,
        ),
    ]
