# Generated by Django 2.2 on 2020-01-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0005_auto_20200125_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificacion',
            old_name='id_usuario',
            new_name='correo_electronico',
        ),
    ]
