# Generated by Django 2.2 on 2020-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0005_auto_20200205_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intercambio',
            name='comentario1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='intercambio',
            name='comentario2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
