# Generated by Django 2.2 on 2020-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSharing', '0006_auto_20200126_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
